spring:
  application.name: membership
  profiles.active: ${NETFLIX_STACK:local}
security.basic.enabled: false
netflix:
  appinfo.name: ${spring.application.name}
  appinfo.region: ${EC2_REGION:us-west-1}
  environment: ${NETFLIX_ENVIRONMENT:test}
eurea:
  client.serviceUrl.defaultZone: http://localhost:8761/eureka/
  instance.leaseRenewalIntervalInSeconds: 3
server.port: 8080
endpoints.health.sensitive: false