spring:
  application.name: recommendations
  profiles.active: ${NETFLIX_STACK:local}
security.basic.enabled: false
netflix:
  appinfo.name: ${spring.application.name}
  appinfo.region: ${EC2_REGION:us-west-1}
  environment: ${NETFLIX_ENVIRONMENT:test}
eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/
server.port: 8081
endpoints.health.sensitive: false
membership.ribbon.DeploymentContextBasedVipAddresses: membership